### ISSUE TITLE
Scraping Prowlarr results in error "AttributeError: 'types.SimpleNamespace' object has no attribute 'seeders'"

### ISSUE THREAD

**Issue by MisterC925** [I-am-PUID-0/pd_zurg#64]
**Describe the bug**

Added a prowlarr instance to the scraper configuration, I can see the searches in the prowlarr logs.

**To Reproduce**

Search for anything either using manual scraper or let plex_debrid run

**Expected behavior**

Search for show/movie using Prowlarr, if found, check against debrid, add to account.

**Screenshots**
```

Aug  2, 2024 00:36:01 - INFO - plex_debrid: Exception in thread Thread-149 (multi_scrape):
Aug  2, 2024 00:36:01 - INFO - plex_debrid: Traceback (most recent call last):
Aug  2, 2024 00:36:01 - INFO - plex_debrid: File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Aug  2, 2024 00:36:01 - INFO - plex_debrid: self.run()
Aug  2, 2024 00:36:01 - INFO - plex_debrid: File "/usr/local/lib/python3.11/threading.py", line 982, in run
Aug  2, 2024 00:36:01 - INFO - plex_debrid: self._target(*self._args, **self._kwargs)
Aug  2, 2024 00:36:01 - INFO - plex_debrid: File "/plex_debrid/scraper/__init__.py", line 56, in multi_scrape
Aug  2, 2024 00:36:01 - INFO - plex_debrid: result[index] = cls.scrape(query, altquery)
Aug  2, 2024 00:36:01 - INFO - plex_debrid: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug  2, 2024 00:36:01 - INFO - plex_debrid: File "/plex_debrid/scraper/services/prowlarr.py", line 44, in scrape
Aug  2, 2024 00:36:01 - INFO - plex_debrid: releases.release('[prowlarr: ' + str(result.indexer) + ']', 'torrent', result.title,[], float(result.size) / 1000000000, [result.magnetUrl],seeders=result.seeders)]
Aug  2, 2024 00:36:01 - INFO - plex_debrid subprocess: [02/08/24 00:35:58] scraping sources [torrentio,prowlarr] for query "TVSHOW.S01" ... done - found 3 releases
Aug  2, 2024 00:36:01 - INFO - plex_debrid: ^^^^^^^^^^^^^^
Aug  2, 2024 00:36:01 - INFO - plex_debrid: AttributeError: 'types.SimpleNamespace' object has no attribute 'seeders'
```

**Please complete the following information:**
 - OS:  Ubuntu
 - Version: 22.04.4 LTS
 - Supporting Applications: Docker

**Additional context**

Not sure if prowlarr is supposed to be working but would be great if so, as I have access to a private prowlarr+torrentio setup.

**Comment by I-am-PUID-0** [comment]
Prowlarr is working in my use, so there may be something else going on in the configuration. 

You can try using `- PD_REPO=mercuryy-1337,plex_debrid,main`, which will allow you to pull other forks of plex_debrid.

I'm closing this issue as it's unrelated to pd_zurg and is a plex_debrid related issue.
